version: "3.8"
services:
  # backend:
  #   image: backend-dev
  #   build:
  #     context: .
  #     dockerfile: dev.Dockerfile
  #   container_name: backend-dev
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=trustcar
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "trustcar@trustcar.fi"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - 16543:80
