version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=test_db_user
      - POSTGRES_PASSWORD=test_db_password
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "trustcar@trustcar.fi"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - 16543:80