name: Lint and Deploy Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: trustcar_test_db
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint 
        run: npm run lint

      - name: Generate database tables
        env:
          DATABASE_URL: postgres://testuser:password@localhost:5432/trustcar_test_db
        run: npx prisma migrate dev --skip-seed
          
      - name: Seed test data
        env:
          DATABASE_URL: postgres://testuser:password@localhost:5432/trustcar_test_db
        run: npx ts-node ./prisma/test-seed.ts

      - name: Test
        env:
          DATABASE_URL: postgres://testuser:password@localhost:5432/trustcar_test_db
          JWT_SECRET: mysecret
        run: npm run test

  deploy:
    permissions: write-all
    needs: [lint_and_test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to production
        run: echo "Deploying to production"

      - name: Deploy via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: echo "$SSH_PRIVATE_KEY"
      - name: Run Command via SSH
        uses: appleboy/ssh-action@master
        with:
          host: carpass.fi
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd trustcar/trustcar-back/
            git checkout main
            git pull
            cd carpass-admin
            npm install
            npm run build
            cp -r dist/* ../public/
            cd ..
            docker-compose -f docker-compose.pro.yml down
            docker-compose -f docker-compose.pro.yml up --build -d
            docker-compose -f docker-compose.pro.yml exec -T backend npm run migrate